### PR TITLE
Map version 1.1

### PR DESCRIPTION
**Pull request by panguitch**
Many changes to the map/game. See internal changelog.

First time I've used Git. Fingers crossed.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
I recommend putting change log notes (map/greyhawkchangelog.txt) into a README.md file (https://github.com/triplea-maps/greyhawk_wars/blob/master/README.md). The contents are then view-able when browsing the repo: https://github.com/triplea-maps/greyhawk_wars

**Comment by DanVanAtta** [comment]
download version updated in: https://github.com/triplea-game/triplea/pull/1267

**Comment by panguitch** [comment]
Huh. Now the map won't run. Gives an error that it can't find the images in the doc folder. Has the necessary file structure changed? What am I missing?

[gwerror.txt](https://github.com/triplea-maps/greyhawk_wars/files/496412/gwerror.txt)

**Comment by DanVanAtta** [comment]
"Greyhawk_Wars/ doc/images/Suel.gif"

There is a space in front of "doc", looks like that should not be there.

**Comment by panguitch** [comment]
I see the space in the error report, but I can't see it in the actual files in explorer, in GitHub on my desktop, or in the commit list https://github.com/triplea-maps/greyhawk_wars/pull/1/commits/cea436019f9d4aaef249e95da947dba0e5d113b6

**Comment by DanVanAtta** [comment]
I'll see if I can help debug a bit later tonight, since this is broken will revert the PR for the moment and give us some time to work through the issues.

**Comment by panguitch** [comment]
Now that 1.9 is released I tried some things to get this map update to work. And failed apparently. The images in the docs folder don't show in the game notes, and when I try to launch the map it fails. No idea why. Runs just fine when I run it from my own files--you can put the zip directly into downloadedMaps 
[Greyhawk_Wars.zip](https://github.com/triplea-maps/greyhawk_wars/files/572720/Greyhawk_Wars.zip)
and it runs fine. I'm probably doing something wrong with Git since I'm a nub and don't really understand it.

**Pull request merged**
